In [1]:
import json
import requests
import pandas as pd
import numpy as np
import seaborn as sns
from boardlib_preprocessing import df_sql, parse_frames_to_holdset, convert_dataframe_to_holds, add_useability_features, upload_holds, flush_backup_holds, upload_climbs_batch, delete_wall

In [4]:
dfg = df_sql('grasshopper', "SELECT * FROM holes", index_col='id')
dfg['x_ft'] = dfg['x']/12 + 6
dfg['y_ft'] = dfg['y']/12
dfg.sort_values('y').head()

    product_id   name   x  ...  mirror_group      x_ft      y_ft
id                         ...
1            1  -64,4 -64  ...             0  0.666667  0.333333
37           1  -48,4 -48  ...             0  2.000000  0.333333
36           1  -56,4 -56  ...             0  1.333333  0.333333
73           1  -32,4 -32  ...             0  3.333333  0.333333
72           1  -40,4 -40  ...             0  2.666667  0.333333

[5 rows x 8 columns]

In [5]:
dfp = df_sql("grasshopper", "SELECT * FROM placements", "id")
dfp = pd.merge(dfp, dfg, left_on="hole_id", right_index=True, how="inner")[['default_placement_role_id', "x_ft", "y_ft"]]
dfp['is_foot'] = (dfp['default_placement_role_id']==4)
dfp

     default_placement_role_id      x_ft       y_ft  is_foot
id
1                            2  2.666667  10.333333    False
2                            2  2.666667   9.666667    False
3                            2  2.666667   9.000000    False
4                            2  2.666667   8.333333    False
5                            2  2.666667   7.666667    False
..                         ...       ...        ...      ...
462                          2  6.333333   8.000000    False
463                          2  6.333333   8.666667    False
464                          2  6.333333   9.333333    False
465                          2  6.333333  10.666667    False
466                          2  6.333333  11.333333    False

[466 rows x 4 columns]

In [9]:
holds = convert_dataframe_to_holds(dfp)
upload_holds('wall-87059ecf9a99',holds)
# delete_wall('wall-e8ced52d826f')

Uploading 466 holds to wall wall-87059ecf9a99...
Endpoint: http://localhost:8000/api/v1/walls/wall-87059ecf9a99/holds
✓ Successfully uploaded 466 holds!

{'id': 'wall-87059ecf9a99'}

In [ ]:
query="""
        SELECT 
            c.uuid,
            c.name,
            cs.angle,
            c.frames,
            cs.difficulty_average,
            cs.quality_average,
            cs.fa_username,
            c.created_at
        FROM climbs c
        JOIN climb_stats cs ON c.uuid = cs.climb_uuid
        WHERE cs.difficulty_average IS NOT NULL
            AND cs.quality_average IS NOT NULL
        ORDER BY cs.ascensionist_count DESC;
    """
df_climbs = df_sql("grasshopper",query)
df_climbs['ascenscionist_count'] = 1
df_climbs

# upload_climbs_batch(
#     df_climbs,
#     'wall-87059ecf9a99'
# )

                                                   name  ...  ascenscionist_count
uuid                                                     ...
7804F10C53CD472BAFD3D02D4035B4A8       cold pup warm up  ...                    1
7804F10C53CD472BAFD3D02D4035B4A8       cold pup warm up  ...                    1
5E56CECB6F544B76B866C0D38EDA312E                  Uffda  ...                    1
EEA439041E4241649D58E1EAFBB9E3AC              Zoolander  ...                    1
EEA439041E4241649D58E1EAFBB9E3AC              Zoolander  ...                    1
...                                                 ...  ...                  ...
1235158B5EE647AC99310829771BCD05              bomboclat  ...                    1
833ef06bc3d547a88b22cd96295e71d2               big easy  ...                    1
93aaf8835a6a4c3da672d16a7694271b          45 until Warm  ...                    1
41018A2538894E70BF8D77A3BFCF671C  Touch my kidneys (V1)  ...                    1
101c9904d3af4b4089556df2aec61ec4    drop those knees v1  ...                    1

[27290 rows x 8 columns]

In [11]:
df_climbs = df_sql("grasshopper","SELECT * FROM climbs")
from sklearn.preprocessing import MinMaxScaler
grades_dict = {}
for i, row in df_climbs.iterrows():
    try:
        holdset = parse_frames_to_holdset(row['frames'])
        for h in [h for l in holdset.values() for h in l]:
            if h not in grades_dict:
                grades_dict[h] = []
            grades_dict[h].append(row['difficulty_average'])
    except:
        continue
scaler = MinMaxScaler(feature_range=(1,100))
df_hold_diff = pd.DataFrame(np.array([[k,1/np.mean(v)] for k, v in grades_dict.items()]), columns=['hold_index','difficulty_level']).set_index('hold_index')
df_hold_diff['difficulty_level'] = np.round(scaler.fit_transform(df_hold_diff[['difficulty_level']])/100,2)
df_hold_diff.sort_values('difficulty_level')

c:\Users\EvanM\anaconda3\envs\DataScience\Lib\site-packages\numpy\_core\fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\EvanM\anaconda3\envs\DataScience\Lib\site-packages\numpy\_core\_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
c:\Users\EvanM\anaconda3\envs\DataScience\Lib\site-packages\sklearn\utils\_array_api.py:794: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
c:\Users\EvanM\anaconda3\envs\DataScience\Lib\site-packages\sklearn\utils\_array_api.py:814: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

            difficulty_level
hold_index
152.0                    NaN
47.0                     NaN
12.0                     NaN
93.0                     NaN
85.0                     NaN
...                      ...
315.0                    NaN
416.0                    NaN
178.0                    NaN
100.0                    NaN
53.0                     NaN

[307 rows x 1 columns]

In [ ]:
query='SELECT * FROM holes'
df_holes = df_sql("decoy", query, index_col='id').astype({'product_id':int, 'name':str,'x':int,'y':int,'mirrored_hole_id':int,'mirror_group':int})
df_holes.head()

In [ ]:
sns.scatterplot(df_holes, x='x',y='y')

### Product 4 is the TB1, Product 5 is the TB2. We need to convert both of these hold-sets to real, physical holds. First step would be aligning them with their real, physical location on the board. Second step would be finding some way to manually add pull_dir+useability features.

I learned from the TB2 installation guide that these hole location measurements are in inches. Additionally, the TB2 DOESN'T HAVE A KICKBOARD! That's crazy, and a bit of a Mandela effect for me. I could swear it had one. But nope.

**The guide also comes with crystal clear hold orientations, and difficulty levels. This is exactly the data I'm looking for! Fuck yeah, Tension!**

In [ ]:
query = "SELECT * FROM placements WHERE layout_id = 2"
df_placements = df_sql("decoy",query,index_col=None).astype({'id':int,'layout_id':int,'hole_id':int,'set_id':int,'default_placement_role_id':int})
df_placements = pd.merge(
    df_placements,
    df_holes,
    left_on='hole_id',
    right_on=df_holes.index,
    how='inner'
)
min_x = df_placements['x'].min()
df_placements.loc[df_placements['id'].isin([950, 935]), 'y'] += 8
df_placements['x_ft'] = (df_placements['x']+8.5-min_x)/12
df_placements['y_ft'] = (df_placements['y']+8)/12
df_placements['is_foot'] = (df_placements['default_placement_role_id']%4==0).astype(int)
df_placements = df_placements[['id','hole_id','x_ft','y_ft','is_foot']].sort_values('id')
print(
    df_placements['x_ft'].max(),
    df_placements['y_ft'].max()
)
df_placements.head()

In [ ]:
decoy_holds = convert_dataframe_to_holds(df_placements)
upload_holds('wall-9e000814e880',decoy_holds)

In [ ]:

flush_backup_holds("wall-e77a688049fb")

In [ ]:
from sklearn.preprocessing import MinMaxScaler
grades_dict = {}
for i, row in df_climbs.iterrows():
    try:
        holdset = parse_frames_to_holdset(row['frames'])
        for h in [h for l in holdset.values() for h in l]:
            if h not in grades_dict:
                grades_dict[h] = []
            grades_dict[h].append(row['difficulty_average'])
    except:
        continue
scaler = MinMaxScaler(feature_range=(1,100))
df_hold_diff = pd.DataFrame(np.array([[k,1/np.mean(v)] for k, v in grades_dict.items()]), columns=['hold_index','difficulty_level']).set_index('hold_index')
df_hold_diff['difficulty_level'] = np.round(scaler.fit_transform(df_hold_diff[['difficulty_level']])/100,2)
df_hold_diff.sort_values('difficulty_level')